# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: leochavesdev
# "service" is the name of this project. This will also be added to your AWS resource names.
service: live052

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1
  environment:
    LIVES_TABLE: !Ref LivesTable
    LIVES_IMAGES_BUCKET: !Ref LivesImagesBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: !GetAtt LivesTable.Arn
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !Join ["/", [!GetAtt LivesImagesBucket.Arn, "*"]]

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"
      - sharp
    external:
      - sharp

layers:
  Sharp:
    name: sharp-layer
    description: sharp package and its binaries.
    path: layers/sharp
    retain: false
    compatibleArchitectures:
      - arm64
    compatibleRuntimes:
      - nodejs20.x

functions:
  createLive:
    handler: src/functions/http/createLive.handler
    events:
      - httpApi:
          path: /lives
          method: POST
  processImage:
    handler: src/functions/triggers/processImage.handler
    layers:
      - !Ref SharpLambdaLayer
    events:
      - s3:
          bucket: !Ref LivesImagesBucket
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true
          rules:
            - prefix: uploads/

resources:
  Resources:
    LivesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LivesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    LivesImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lives-images-leochaves
